/**
 * PDFGen API
 * The PDFGen API for HTML to PDF generation.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pdfgen.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GeneratePDFRequest {
    'html': string;
    'variables'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "html",
            "baseName": "html",
            "type": "string"
        },
        {
            "name": "variables",
            "baseName": "variables",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return GeneratePDFRequest.attributeTypeMap;
    }
}

