/**
 * PDFGen API
 * The PDFGen API for HTML to PDF generation.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@pdfgen.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { JobResponse } from './jobResponse';

export class ListJobsResponse {
    'jobs': Array<JobResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "jobs",
            "baseName": "jobs",
            "type": "Array<JobResponse>"
        }    ];

    static getAttributeTypeMap() {
        return ListJobsResponse.attributeTypeMap;
    }
}

